//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_Agricultural_Consultant_DBEntities : DbContext
    {
        public Online_Agricultural_Consultant_DBEntities()
            : base("name=Online_Agricultural_Consultant_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblArticle> tblArticles { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblExpertDetail> tblExpertDetails { get; set; }
        public virtual DbSet<tblFarmerDetail> tblFarmerDetails { get; set; }
        public virtual DbSet<tblKisaanKendraDetail> tblKisaanKendraDetails { get; set; }
        public virtual DbSet<tblQueryDetail> tblQueryDetails { get; set; }
        public virtual DbSet<tblRegularIssue> tblRegularIssues { get; set; }
        public virtual DbSet<tblSiteVisit> tblSiteVisits { get; set; }
        public virtual DbSet<tblSoilTesting> tblSoilTestings { get; set; }
        public virtual DbSet<tblStaffDetail> tblStaffDetails { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblStatusDetail> tblStatusDetails { get; set; }
        public virtual DbSet<tblVillage> tblVillages { get; set; }
    }
}
