//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int ID { get; set; }
        public string AdminUserID { get; set; }
        public string Password { get; set; }
    }
}
