//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpertDetail
    {
        public int ID { get; set; }
        public string ExpertId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string Dob { get; set; }
        public string Gender { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string ExpertIn { get; set; }
        public string SpecialistIn { get; set; }
        public string EducationLevel { get; set; }
        public string EducationDetails { get; set; }
        public string CertificateDetails { get; set; }
        public Nullable<int> ExperinceInYears { get; set; }
        public string Availibility { get; set; }
        public string AadharNo { get; set; }
        public string PanNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Status { get; set; }
    }
}
