//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFarmerDetail
    {
        public int ID { get; set; }
        public string FarmerId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public Nullable<int> PINCode { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string FarmerType { get; set; }
        public string FarmerCategory { get; set; }
        public string AadharNo { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public string DeletedDate { get; set; }
        public string Status { get; set; }
    }
}
