//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKisaanKendraDetail
    {
        public int ID { get; set; }
        public string KKId { get; set; }
        public string Password { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string Village { get; set; }
        public Nullable<int> NoOfFarmers { get; set; }
        public Nullable<int> NoOfRegApp { get; set; }
        public Nullable<int> NoOfSiteVisitApp { get; set; }
        public string Status { get; set; }
        public string Owner { get; set; }
        public string Mobile { get; set; }
    }
}
