//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegularIssue
    {
        public int IssueId { get; set; }
        public string FarmerID { get; set; }
        public string IssueType { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string SolvedBy { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public string FeedBack { get; set; }
        public string Status { get; set; }
        public string Solution { get; set; }
    }
}
