//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffDetail
    {
        public int ID { get; set; }
        public string EmpId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string FullAddress { get; set; }
        public string Image { get; set; }
        public string Department { get; set; }
        public string AadharNo { get; set; }
        public string PanNo { get; set; }
        public string RoleID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Status { get; set; }
    }
}
