//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoilTesting
    {
        public int ID { get; set; }
        public string TestId { get; set; }
        public string FarmerId { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string SoilType { get; set; }
        public string Nutrient { get; set; }
        public string Acidity { get; set; }
        public string PhLevel { get; set; }
        public string TestedBy { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public string HealthCardNo { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public Nullable<int> VisitIntervalInHrs { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string Feedback { get; set; }
    }
}
