//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiteVisit
    {
        public int ID { get; set; }
        public string ApplicationId { get; set; }
        public string FarmerId { get; set; }
        public string FieldType { get; set; }
        public string FieldLocation { get; set; }
        public string CropDesc { get; set; }
        public string ProblemDesc { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public string AssignedAsst { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public Nullable<int> VisitIntervalInHrs { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string Feedback { get; set; }
    }
}
