//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Agricultural_Consultant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatusDetail
    {
        public int ID { get; set; }
        public string StatusId { get; set; }
        public string ApplicationNo { get; set; }
        public string ApplicationType { get; set; }
        public string FarmerId { get; set; }
        public string UpdatedBy { get; set; }
        public string Content { get; set; }
    }
}
